<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BoardCertificationTypeSeeder extends Seeder
{
    public function run(): void
    {
        $types = [
            // ── ABMS (American Board of Medical Specialties) — Physician Boards ──
            ['slug' => 'abim_im',           'abbreviation' => 'ABIM',       'name' => 'Internal Medicine',                                'issuing_body' => 'American Board of Internal Medicine',           'discipline' => 'physician',    'specialty' => 'Internal Medicine',              'recert_years' => 10, 'requires_cme' => true, 'notes' => 'ABMS member board. MOC (Maintenance of Certification) required.'],
            ['slug' => 'abim_cardio',       'abbreviation' => 'ABIM',       'name' => 'Cardiovascular Disease',                           'issuing_body' => 'American Board of Internal Medicine',           'discipline' => 'physician',    'specialty' => 'Cardiology',                     'recert_years' => 10, 'requires_cme' => true, 'notes' => 'Subspecialty of Internal Medicine.'],
            ['slug' => 'abim_gastro',       'abbreviation' => 'ABIM',       'name' => 'Gastroenterology',                                 'issuing_body' => 'American Board of Internal Medicine',           'discipline' => 'physician',    'specialty' => 'Gastroenterology',               'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'abim_pulm',         'abbreviation' => 'ABIM',       'name' => 'Pulmonary Disease',                                'issuing_body' => 'American Board of Internal Medicine',           'discipline' => 'physician',    'specialty' => 'Pulmonology',                    'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'abim_endo',         'abbreviation' => 'ABIM',       'name' => 'Endocrinology, Diabetes & Metabolism',             'issuing_body' => 'American Board of Internal Medicine',           'discipline' => 'physician',    'specialty' => 'Endocrinology',                  'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'abim_nephro',       'abbreviation' => 'ABIM',       'name' => 'Nephrology',                                       'issuing_body' => 'American Board of Internal Medicine',           'discipline' => 'physician',    'specialty' => 'Nephrology',                     'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'abim_rheum',        'abbreviation' => 'ABIM',       'name' => 'Rheumatology',                                     'issuing_body' => 'American Board of Internal Medicine',           'discipline' => 'physician',    'specialty' => 'Rheumatology',                   'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'abim_id',           'abbreviation' => 'ABIM',       'name' => 'Infectious Disease',                               'issuing_body' => 'American Board of Internal Medicine',           'discipline' => 'physician',    'specialty' => 'Infectious Disease',             'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'abim_onc',          'abbreviation' => 'ABIM',       'name' => 'Medical Oncology',                                 'issuing_body' => 'American Board of Internal Medicine',           'discipline' => 'physician',    'specialty' => 'Oncology',                       'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'abim_hem',          'abbreviation' => 'ABIM',       'name' => 'Hematology',                                       'issuing_body' => 'American Board of Internal Medicine',           'discipline' => 'physician',    'specialty' => 'Hematology',                     'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'abim_geriatric',    'abbreviation' => 'ABIM',       'name' => 'Geriatric Medicine',                               'issuing_body' => 'American Board of Internal Medicine',           'discipline' => 'physician',    'specialty' => 'Geriatric Medicine',             'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'abfm',              'abbreviation' => 'ABFM',       'name' => 'Family Medicine',                                  'issuing_body' => 'American Board of Family Medicine',             'discipline' => 'physician',    'specialty' => 'Family Medicine',                'recert_years' => 10, 'requires_cme' => true, 'notes' => 'Continuous certification model since 2019.'],
            ['slug' => 'abp_peds',          'abbreviation' => 'ABP',        'name' => 'General Pediatrics',                               'issuing_body' => 'American Board of Pediatrics',                  'discipline' => 'physician',    'specialty' => 'Pediatrics',                     'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'abs_surgery',       'abbreviation' => 'ABS',        'name' => 'General Surgery',                                  'issuing_body' => 'American Board of Surgery',                     'discipline' => 'physician',    'specialty' => 'General Surgery',                'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'abos_ortho',        'abbreviation' => 'ABOS',       'name' => 'Orthopedic Surgery',                               'issuing_body' => 'American Board of Orthopaedic Surgery',         'discipline' => 'physician',    'specialty' => 'Orthopedic Surgery',             'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'abog',              'abbreviation' => 'ABOG',       'name' => 'Obstetrics & Gynecology',                          'issuing_body' => 'American Board of Obstetrics and Gynecology',   'discipline' => 'physician',    'specialty' => 'OB/GYN',                         'recert_years' => 6,  'requires_cme' => true, 'notes' => '6-year MOC cycle.'],
            ['slug' => 'abpn_psych',        'abbreviation' => 'ABPN',       'name' => 'Psychiatry',                                       'issuing_body' => 'American Board of Psychiatry and Neurology',    'discipline' => 'physician',    'specialty' => 'Psychiatry',                     'recert_years' => 10, 'requires_cme' => true, 'notes' => 'Certifies psychiatrists and neurologists.'],
            ['slug' => 'abpn_neuro',        'abbreviation' => 'ABPN',       'name' => 'Neurology',                                        'issuing_body' => 'American Board of Psychiatry and Neurology',    'discipline' => 'physician',    'specialty' => 'Neurology',                      'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'abpn_child',        'abbreviation' => 'ABPN',       'name' => 'Child & Adolescent Psychiatry',                    'issuing_body' => 'American Board of Psychiatry and Neurology',    'discipline' => 'physician',    'specialty' => 'Child & Adolescent Psychiatry',  'recert_years' => 10, 'requires_cme' => true, 'notes' => 'Subspecialty of Psychiatry.'],
            ['slug' => 'abpn_addiction',    'abbreviation' => 'ABPN',       'name' => 'Addiction Psychiatry',                             'issuing_body' => 'American Board of Psychiatry and Neurology',    'discipline' => 'physician',    'specialty' => 'Addiction Psychiatry',            'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'abem',              'abbreviation' => 'ABEM',       'name' => 'Emergency Medicine',                               'issuing_body' => 'American Board of Emergency Medicine',          'discipline' => 'physician',    'specialty' => 'Emergency Medicine',             'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'aba_anes',          'abbreviation' => 'ABA',        'name' => 'Anesthesiology',                                   'issuing_body' => 'American Board of Anesthesiology',              'discipline' => 'physician',    'specialty' => 'Anesthesiology',                 'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'abr_rad',           'abbreviation' => 'ABR',        'name' => 'Diagnostic Radiology',                             'issuing_body' => 'American Board of Radiology',                   'discipline' => 'physician',    'specialty' => 'Diagnostic Radiology',           'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'abpath',            'abbreviation' => 'ABPath',     'name' => 'Anatomic & Clinical Pathology',                    'issuing_body' => 'American Board of Pathology',                   'discipline' => 'physician',    'specialty' => 'Pathology',                      'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'abd_derm',          'abbreviation' => 'ABD',        'name' => 'Dermatology',                                      'issuing_body' => 'American Board of Dermatology',                 'discipline' => 'physician',    'specialty' => 'Dermatology',                    'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'abo_ophth',         'abbreviation' => 'ABO',        'name' => 'Ophthalmology',                                    'issuing_body' => 'American Board of Ophthalmology',               'discipline' => 'physician',    'specialty' => 'Ophthalmology',                  'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'aboto',             'abbreviation' => 'ABOto',      'name' => 'Otolaryngology — Head & Neck Surgery',             'issuing_body' => 'American Board of Otolaryngology',              'discipline' => 'physician',    'specialty' => 'Otolaryngology',                 'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'abu_urology',       'abbreviation' => 'ABU',        'name' => 'Urology',                                          'issuing_body' => 'American Board of Urology',                     'discipline' => 'physician',    'specialty' => 'Urology',                        'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'abpmr',             'abbreviation' => 'ABPMR',      'name' => 'Physical Medicine & Rehabilitation',               'issuing_body' => 'American Board of Physical Medicine and Rehab', 'discipline' => 'physician',    'specialty' => 'PM&R',                           'recert_years' => 10, 'requires_cme' => true, 'notes' => null],

            // ── NURSING CERTIFICATIONS ──
            ['slug' => 'ancc_pmhnp',        'abbreviation' => 'PMHNP-BC',   'name' => 'Psychiatric-Mental Health NP — Board Certified',   'issuing_body' => 'ANCC',                                          'discipline' => 'nursing',      'specialty' => 'Psychiatric-Mental Health',      'recert_years' => 5,  'requires_cme' => true, 'notes' => 'American Nurses Credentialing Center. 75 CE hours per 5 years.'],
            ['slug' => 'ancc_fnp',          'abbreviation' => 'FNP-BC',     'name' => 'Family NP — Board Certified',                      'issuing_body' => 'ANCC',                                          'discipline' => 'nursing',      'specialty' => 'Family',                         'recert_years' => 5,  'requires_cme' => true, 'notes' => null],
            ['slug' => 'ancc_agnp',         'abbreviation' => 'AGPCNP-BC',  'name' => 'Adult-Gerontology Primary Care NP-BC',             'issuing_body' => 'ANCC',                                          'discipline' => 'nursing',      'specialty' => 'Adult-Gerontology',              'recert_years' => 5,  'requires_cme' => true, 'notes' => null],
            ['slug' => 'ancc_acnp',         'abbreviation' => 'AGACNP-BC',  'name' => 'Adult-Gerontology Acute Care NP-BC',               'issuing_body' => 'ANCC',                                          'discipline' => 'nursing',      'specialty' => 'Acute Care',                     'recert_years' => 5,  'requires_cme' => true, 'notes' => null],
            ['slug' => 'aanp_fnp',          'abbreviation' => 'FNP-C',      'name' => 'Family NP — Certified (AANP)',                     'issuing_body' => 'AANP Certification Board',                      'discipline' => 'nursing',      'specialty' => 'Family',                         'recert_years' => 5,  'requires_cme' => true, 'notes' => 'Alternative to ANCC FNP-BC.'],
            ['slug' => 'aanp_agnp',         'abbreviation' => 'A-GNP',      'name' => 'Adult-Gerontology NP — Certified (AANP)',          'issuing_body' => 'AANP Certification Board',                      'discipline' => 'nursing',      'specialty' => 'Adult-Gerontology',              'recert_years' => 5,  'requires_cme' => true, 'notes' => null],
            ['slug' => 'ncc_whnp',          'abbreviation' => 'WHNP-BC',    'name' => 'Women\'s Health NP — Board Certified',             'issuing_body' => 'NCC',                                           'discipline' => 'nursing',      'specialty' => 'Women\'s Health',                'recert_years' => 5,  'requires_cme' => true, 'notes' => 'National Certification Corporation.'],
            ['slug' => 'pncb_cpnp',         'abbreviation' => 'CPNP-PC',    'name' => 'Certified Pediatric NP — Primary Care',            'issuing_body' => 'PNCB',                                          'discipline' => 'nursing',      'specialty' => 'Pediatrics',                     'recert_years' => 5,  'requires_cme' => true, 'notes' => 'Pediatric Nursing Certification Board.'],
            ['slug' => 'nbcrna',            'abbreviation' => 'CRNA',       'name' => 'Certified Registered Nurse Anesthetist',           'issuing_body' => 'NBCRNA',                                        'discipline' => 'nursing',      'specialty' => 'Nurse Anesthesia',               'recert_years' => 4,  'requires_cme' => true, 'notes' => 'CPC (Continued Professional Certification) program. 100 CE credits per 4 years.'],
            ['slug' => 'amcb_cnm',          'abbreviation' => 'CNM',        'name' => 'Certified Nurse-Midwife',                          'issuing_body' => 'AMCB',                                          'discipline' => 'nursing',      'specialty' => 'Nurse Midwifery',                'recert_years' => 5,  'requires_cme' => true, 'notes' => 'American Midwifery Certification Board.'],

            // ── PHYSICIAN ASSISTANT ──
            ['slug' => 'nccpa_pac',         'abbreviation' => 'PA-C',       'name' => 'Physician Assistant — Certified',                  'issuing_body' => 'NCCPA',                                         'discipline' => 'physician_assistant', 'specialty' => 'General', 'recert_years' => 10, 'requires_cme' => true, 'notes' => 'National Commission on Certification of PAs. 100 CME per 2-year cycle.'],

            // ── PSYCHOLOGY ──
            ['slug' => 'abpp_clinical',     'abbreviation' => 'ABPP',       'name' => 'Board Certified in Clinical Psychology',           'issuing_body' => 'American Board of Professional Psychology',     'discipline' => 'psychology',   'specialty' => 'Clinical Psychology',            'recert_years' => null, 'requires_cme' => true, 'notes' => 'Voluntary board specialty certification for psychologists.'],
            ['slug' => 'abpp_neuro',        'abbreviation' => 'ABPP',       'name' => 'Board Certified in Clinical Neuropsychology',      'issuing_body' => 'American Board of Professional Psychology',     'discipline' => 'psychology',   'specialty' => 'Neuropsychology',                'recert_years' => null, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'eppp',              'abbreviation' => 'EPPP',       'name' => 'Examination for Professional Practice in Psych',   'issuing_body' => 'ASPPB',                                         'discipline' => 'psychology',   'specialty' => 'Psychology (General)',            'recert_years' => null, 'requires_cme' => false, 'notes' => 'Required exam for psychology licensure in all US jurisdictions. One-time pass.'],

            // ── SOCIAL WORK ──
            ['slug' => 'aswb_clinical',     'abbreviation' => 'ASWB',       'name' => 'ASWB Clinical Examination',                        'issuing_body' => 'Association of Social Work Boards',             'discipline' => 'social_work',  'specialty' => 'Clinical Social Work',           'recert_years' => null, 'requires_cme' => false, 'notes' => 'Required exam for LCSW licensure. One-time pass.'],
            ['slug' => 'acsw',              'abbreviation' => 'ACSW',       'name' => 'Academy of Certified Social Workers',              'issuing_body' => 'NASW',                                          'discipline' => 'social_work',  'specialty' => 'Social Work',                    'recert_years' => 3,  'requires_cme' => true, 'notes' => 'National Association of Social Workers credential.'],

            // ── COUNSELING ──
            ['slug' => 'nbcc_ncc',          'abbreviation' => 'NCC',        'name' => 'National Certified Counselor',                     'issuing_body' => 'NBCC',                                          'discipline' => 'counseling',   'specialty' => 'Counseling (General)',            'recert_years' => 5,  'requires_cme' => true, 'notes' => 'National Board for Certified Counselors. 100 CE hours per 5 years.'],
            ['slug' => 'nbcc_ccmhc',        'abbreviation' => 'CCMHC',      'name' => 'Certified Clinical Mental Health Counselor',       'issuing_body' => 'NBCC',                                          'discipline' => 'counseling',   'specialty' => 'Mental Health Counseling',       'recert_years' => 5,  'requires_cme' => true, 'notes' => null],
            ['slug' => 'nbcc_mac',          'abbreviation' => 'MAC',        'name' => 'Master Addictions Counselor',                      'issuing_body' => 'NBCC',                                          'discipline' => 'counseling',   'specialty' => 'Addiction Counseling',            'recert_years' => 5,  'requires_cme' => true, 'notes' => null],
            ['slug' => 'aamft_approved',    'abbreviation' => 'AAMFT-AS',   'name' => 'AAMFT Approved Supervisor',                        'issuing_body' => 'AAMFT',                                         'discipline' => 'counseling',   'specialty' => 'Marriage & Family Therapy',      'recert_years' => 5,  'requires_cme' => true, 'notes' => 'Supervisor designation from AAMFT.'],

            // ── THERAPY & REHABILITATION ──
            ['slug' => 'abpts_ocs',         'abbreviation' => 'OCS',        'name' => 'Orthopedic Clinical Specialist',                   'issuing_body' => 'American Board of Physical Therapy Specialties','discipline' => 'therapy',      'specialty' => 'Orthopedic Physical Therapy',    'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'abpts_ncs',         'abbreviation' => 'NCS',        'name' => 'Neurologic Clinical Specialist',                   'issuing_body' => 'American Board of Physical Therapy Specialties','discipline' => 'therapy',      'specialty' => 'Neurologic Physical Therapy',    'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'abpts_scs',         'abbreviation' => 'SCS',        'name' => 'Sports Clinical Specialist',                       'issuing_body' => 'American Board of Physical Therapy Specialties','discipline' => 'therapy',      'specialty' => 'Sports Physical Therapy',        'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'asha_ccc_slp',      'abbreviation' => 'CCC-SLP',    'name' => 'Certificate of Clinical Competence in SLP',        'issuing_body' => 'ASHA',                                          'discipline' => 'therapy',      'specialty' => 'Speech-Language Pathology',      'recert_years' => 3,  'requires_cme' => true, 'notes' => 'American Speech-Language-Hearing Association. 30 CE per 3 years.'],
            ['slug' => 'asha_ccc_a',        'abbreviation' => 'CCC-A',      'name' => 'Certificate of Clinical Competence in Audiology',  'issuing_body' => 'ASHA',                                          'discipline' => 'therapy',      'specialty' => 'Audiology',                      'recert_years' => 3,  'requires_cme' => true, 'notes' => null],
            ['slug' => 'nbcot_otr',         'abbreviation' => 'OTR/L',      'name' => 'Registered Occupational Therapist',                'issuing_body' => 'NBCOT',                                         'discipline' => 'therapy',      'specialty' => 'Occupational Therapy',           'recert_years' => 3,  'requires_cme' => true, 'notes' => 'National Board for Certification in OT. 36 PDUs per 3 years.'],
            ['slug' => 'nbrc_rrt',          'abbreviation' => 'RRT',        'name' => 'Registered Respiratory Therapist',                 'issuing_body' => 'NBRC',                                          'discipline' => 'therapy',      'specialty' => 'Respiratory Therapy',            'recert_years' => 5,  'requires_cme' => true, 'notes' => null],

            // ── BEHAVIOR ANALYSIS ──
            ['slug' => 'bacb_bcba',         'abbreviation' => 'BCBA',       'name' => 'Board Certified Behavior Analyst',                 'issuing_body' => 'BACB',                                          'discipline' => 'allied_health','specialty' => 'Applied Behavior Analysis',      'recert_years' => 2,  'requires_cme' => true, 'notes' => 'Behavior Analyst Certification Board. 32 CE per 2 years.'],
            ['slug' => 'bacb_bcaba',        'abbreviation' => 'BCaBA',      'name' => 'Board Certified Assistant Behavior Analyst',       'issuing_body' => 'BACB',                                          'discipline' => 'allied_health','specialty' => 'Applied Behavior Analysis',      'recert_years' => 2,  'requires_cme' => true, 'notes' => 'Supervised by BCBA.'],

            // ── DENTAL ──
            ['slug' => 'ada_gp',            'abbreviation' => 'FAGD',       'name' => 'Fellow, Academy of General Dentistry',             'issuing_body' => 'AGD',                                           'discipline' => 'dental',       'specialty' => 'General Dentistry',              'recert_years' => null, 'requires_cme' => true, 'notes' => 'Academy of General Dentistry fellowship.'],
            ['slug' => 'abo_ortho',         'abbreviation' => 'ABO-Ortho',  'name' => 'American Board of Orthodontics Diplomate',         'issuing_body' => 'ABO',                                           'discipline' => 'dental',       'specialty' => 'Orthodontics',                   'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
            ['slug' => 'aboms',             'abbreviation' => 'ABOMS',      'name' => 'American Board of Oral & Maxillofacial Surgery',   'issuing_body' => 'ABOMS',                                         'discipline' => 'dental',       'specialty' => 'Oral & Maxillofacial Surgery',   'recert_years' => 10, 'requires_cme' => true, 'notes' => null],
        ];

        foreach ($types as $type) {
            DB::table('board_certification_types')->updateOrInsert(
                ['slug' => $type['slug']],
                $type
            );
        }
    }
}
