<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LicenseTypeSeeder extends Seeder
{
    public function run(): void
    {
        $types = [
            // Physicians
            ['slug' => 'md',     'abbreviation' => 'MD',       'name' => 'Doctor of Medicine',                          'discipline' => 'physician',      'education_requirement' => 'MD',    'requires_supervision' => false, 'can_prescribe' => true,  'is_independent' => true,  'scope_notes' => 'Full medical practice authority. Board certification in specialty recommended.', 'sort_order' => 1],
            ['slug' => 'do',     'abbreviation' => 'DO',       'name' => 'Doctor of Osteopathic Medicine',              'discipline' => 'physician',      'education_requirement' => 'DO',    'requires_supervision' => false, 'can_prescribe' => true,  'is_independent' => true,  'scope_notes' => 'Full medical practice authority with osteopathic training. Equivalent scope to MD.', 'sort_order' => 2],
            ['slug' => 'dpm',    'abbreviation' => 'DPM',      'name' => 'Doctor of Podiatric Medicine',                'discipline' => 'physician',      'education_requirement' => 'DPM',   'requires_supervision' => false, 'can_prescribe' => true,  'is_independent' => true,  'scope_notes' => 'Foot and ankle medicine and surgery.', 'sort_order' => 3],

            // Advanced Practice Nursing
            ['slug' => 'aprn',   'abbreviation' => 'APRN',     'name' => 'Advanced Practice Registered Nurse',          'discipline' => 'nursing',        'education_requirement' => 'MSN/DNP', 'requires_supervision' => false, 'can_prescribe' => true, 'is_independent' => true, 'scope_notes' => 'Umbrella term for NPs, CNMs, CRNAs, CNSs. Independent practice in full-authority states.', 'sort_order' => 10],
            ['slug' => 'np',     'abbreviation' => 'NP',       'name' => 'Nurse Practitioner',                          'discipline' => 'nursing',        'education_requirement' => 'MSN/DNP', 'requires_supervision' => false, 'can_prescribe' => true, 'is_independent' => true, 'scope_notes' => 'Primary and specialty care. Full/reduced/restricted authority varies by state.', 'sort_order' => 11],
            ['slug' => 'pmhnp',  'abbreviation' => 'PMHNP',    'name' => 'Psychiatric-Mental Health Nurse Practitioner','discipline' => 'nursing',        'education_requirement' => 'MSN/DNP', 'requires_supervision' => false, 'can_prescribe' => true, 'is_independent' => true, 'scope_notes' => 'Psychiatric assessment, diagnosis, medication management. Can prescribe controlled substances in most states.', 'sort_order' => 12],
            ['slug' => 'fnp',    'abbreviation' => 'FNP',      'name' => 'Family Nurse Practitioner',                   'discipline' => 'nursing',        'education_requirement' => 'MSN/DNP', 'requires_supervision' => false, 'can_prescribe' => true, 'is_independent' => true, 'scope_notes' => 'Primary care across lifespan. Most common NP specialty.', 'sort_order' => 13],
            ['slug' => 'agnp',   'abbreviation' => 'AGNP',     'name' => 'Adult-Gerontology Nurse Practitioner',        'discipline' => 'nursing',        'education_requirement' => 'MSN/DNP', 'requires_supervision' => false, 'can_prescribe' => true, 'is_independent' => true, 'scope_notes' => 'Adult and geriatric primary/acute care.', 'sort_order' => 14],
            ['slug' => 'pnp',    'abbreviation' => 'PNP',      'name' => 'Pediatric Nurse Practitioner',                'discipline' => 'nursing',        'education_requirement' => 'MSN/DNP', 'requires_supervision' => false, 'can_prescribe' => true, 'is_independent' => true, 'scope_notes' => 'Pediatric primary and acute care.', 'sort_order' => 15],
            ['slug' => 'whnp',   'abbreviation' => 'WHNP',     'name' => 'Women\'s Health Nurse Practitioner',          'discipline' => 'nursing',        'education_requirement' => 'MSN/DNP', 'requires_supervision' => false, 'can_prescribe' => true, 'is_independent' => true, 'scope_notes' => 'Women\'s reproductive and primary health.', 'sort_order' => 16],
            ['slug' => 'crna',   'abbreviation' => 'CRNA',     'name' => 'Certified Registered Nurse Anesthetist',      'discipline' => 'nursing',        'education_requirement' => 'DNP',     'requires_supervision' => false, 'can_prescribe' => true, 'is_independent' => true, 'scope_notes' => 'Anesthesia services. Supervision requirements vary by state and facility.', 'sort_order' => 17],
            ['slug' => 'cnm',    'abbreviation' => 'CNM',      'name' => 'Certified Nurse Midwife',                     'discipline' => 'nursing',        'education_requirement' => 'MSN/DNP', 'requires_supervision' => false, 'can_prescribe' => true, 'is_independent' => true, 'scope_notes' => 'Midwifery, reproductive/women\'s health, newborn care.', 'sort_order' => 18],
            ['slug' => 'cns',    'abbreviation' => 'CNS',      'name' => 'Clinical Nurse Specialist',                   'discipline' => 'nursing',        'education_requirement' => 'MSN/DNP', 'requires_supervision' => false, 'can_prescribe' => false, 'is_independent' => false, 'scope_notes' => 'Expert clinical practice. Prescriptive authority varies by state.', 'sort_order' => 19],
            ['slug' => 'rn',     'abbreviation' => 'RN',       'name' => 'Registered Nurse',                            'discipline' => 'nursing',        'education_requirement' => 'BSN/ADN', 'requires_supervision' => true,  'can_prescribe' => false, 'is_independent' => false, 'scope_notes' => 'Nursing assessment, care planning, patient education, medication administration.', 'sort_order' => 20],
            ['slug' => 'lpn',    'abbreviation' => 'LPN/LVN',  'name' => 'Licensed Practical/Vocational Nurse',         'discipline' => 'nursing',        'education_requirement' => 'Certificate', 'requires_supervision' => true, 'can_prescribe' => false, 'is_independent' => false, 'scope_notes' => 'Basic nursing care under RN/physician supervision.', 'sort_order' => 21],

            // Physician Assistant
            ['slug' => 'pa',     'abbreviation' => 'PA-C',     'name' => 'Physician Assistant — Certified',             'discipline' => 'physician_assistant', 'education_requirement' => 'MPAS/MMS', 'requires_supervision' => false, 'can_prescribe' => true, 'is_independent' => true, 'scope_notes' => 'Medical practice with collaborative agreements in some states. Full prescriptive authority in most states.', 'sort_order' => 25],

            // Psychology
            ['slug' => 'psyd',   'abbreviation' => 'PsyD',     'name' => 'Doctor of Psychology',                        'discipline' => 'psychology',     'education_requirement' => 'PsyD',  'requires_supervision' => false, 'can_prescribe' => false, 'is_independent' => true,  'scope_notes' => 'Clinical psychology — assessment, diagnosis, psychotherapy. Prescribing in 5 states (IL, IA, ID, LA, NM).', 'sort_order' => 30],
            ['slug' => 'phd_psych', 'abbreviation' => 'PhD',   'name' => 'Doctor of Philosophy in Psychology',          'discipline' => 'psychology',     'education_requirement' => 'PhD',   'requires_supervision' => false, 'can_prescribe' => false, 'is_independent' => true,  'scope_notes' => 'Clinical/counseling psychology. Research-oriented doctoral degree.', 'sort_order' => 31],
            ['slug' => 'lp',     'abbreviation' => 'LP',       'name' => 'Licensed Psychologist',                       'discipline' => 'psychology',     'education_requirement' => 'PhD/PsyD', 'requires_supervision' => false, 'can_prescribe' => false, 'is_independent' => true, 'scope_notes' => 'Licensed for independent psychology practice. Title varies by state.', 'sort_order' => 32],

            // Social Work
            ['slug' => 'lcsw',   'abbreviation' => 'LCSW',     'name' => 'Licensed Clinical Social Worker',             'discipline' => 'social_work',    'education_requirement' => 'MSW',   'requires_supervision' => false, 'can_prescribe' => false, 'is_independent' => true,  'scope_notes' => 'Clinical social work — psychotherapy, assessment, advocacy. Requires post-masters supervised hours.', 'sort_order' => 35],
            ['slug' => 'lmsw',   'abbreviation' => 'LMSW',     'name' => 'Licensed Master Social Worker',               'discipline' => 'social_work',    'education_requirement' => 'MSW',   'requires_supervision' => true,  'can_prescribe' => false, 'is_independent' => false, 'scope_notes' => 'Masters-level social work. Working toward independent licensure (LCSW).', 'sort_order' => 36],
            ['slug' => 'lsw',    'abbreviation' => 'LSW',      'name' => 'Licensed Social Worker',                      'discipline' => 'social_work',    'education_requirement' => 'BSW/MSW', 'requires_supervision' => true, 'can_prescribe' => false, 'is_independent' => false, 'scope_notes' => 'Non-clinical social work services under supervision.', 'sort_order' => 37],

            // Counseling
            ['slug' => 'lpc',    'abbreviation' => 'LPC',      'name' => 'Licensed Professional Counselor',             'discipline' => 'counseling',     'education_requirement' => 'MA/MS', 'requires_supervision' => false, 'can_prescribe' => false, 'is_independent' => true,  'scope_notes' => 'Independent counseling practice. Title varies: LMHC, LCPC, LPCC depending on state.', 'sort_order' => 40],
            ['slug' => 'lmhc',   'abbreviation' => 'LMHC',     'name' => 'Licensed Mental Health Counselor',            'discipline' => 'counseling',     'education_requirement' => 'MA/MS', 'requires_supervision' => false, 'can_prescribe' => false, 'is_independent' => true,  'scope_notes' => 'Same scope as LPC — state title variation (NY, FL, IN, etc.).', 'sort_order' => 41],
            ['slug' => 'lmft',   'abbreviation' => 'LMFT',     'name' => 'Licensed Marriage & Family Therapist',        'discipline' => 'counseling',     'education_requirement' => 'MA/MS', 'requires_supervision' => false, 'can_prescribe' => false, 'is_independent' => true,  'scope_notes' => 'Marriage, family, and relational therapy. Requires specialized MFT program.', 'sort_order' => 42],
            ['slug' => 'lcadc',  'abbreviation' => 'LCADC',    'name' => 'Licensed Clinical Alcohol & Drug Counselor',  'discipline' => 'counseling',     'education_requirement' => 'MA/MS', 'requires_supervision' => false, 'can_prescribe' => false, 'is_independent' => true,  'scope_notes' => 'Substance use disorder counseling. Title varies: LCADC, LCDC, LADC, CASAC.', 'sort_order' => 43],
            ['slug' => 'lac',    'abbreviation' => 'LAC',      'name' => 'Licensed Associate Counselor',                'discipline' => 'counseling',     'education_requirement' => 'MA/MS', 'requires_supervision' => true,  'can_prescribe' => false, 'is_independent' => false, 'scope_notes' => 'Pre-independent counseling license. Working toward full LPC under supervision.', 'sort_order' => 44],

            // Therapy & Rehabilitation
            ['slug' => 'pt',     'abbreviation' => 'PT',       'name' => 'Physical Therapist',                          'discipline' => 'therapy',        'education_requirement' => 'DPT',   'requires_supervision' => false, 'can_prescribe' => false, 'is_independent' => true,  'scope_notes' => 'Movement and rehabilitation. Direct access in most states.', 'sort_order' => 50],
            ['slug' => 'pta',    'abbreviation' => 'PTA',      'name' => 'Physical Therapist Assistant',                'discipline' => 'therapy',        'education_requirement' => 'AAS',   'requires_supervision' => true,  'can_prescribe' => false, 'is_independent' => false, 'scope_notes' => 'Assists PT with treatment under direct supervision.', 'sort_order' => 51],
            ['slug' => 'ot',     'abbreviation' => 'OT',       'name' => 'Occupational Therapist',                      'discipline' => 'therapy',        'education_requirement' => 'MOT/OTD', 'requires_supervision' => false, 'can_prescribe' => false, 'is_independent' => true, 'scope_notes' => 'Activities of daily living, adaptive skills, mental health OT.', 'sort_order' => 52],
            ['slug' => 'ota',    'abbreviation' => 'OTA/COTA', 'name' => 'Occupational Therapy Assistant',              'discipline' => 'therapy',        'education_requirement' => 'AAS',   'requires_supervision' => true,  'can_prescribe' => false, 'is_independent' => false, 'scope_notes' => 'Assists OT with treatment under supervision.', 'sort_order' => 53],
            ['slug' => 'slp',    'abbreviation' => 'SLP/CCC-SLP', 'name' => 'Speech-Language Pathologist',              'discipline' => 'therapy',        'education_requirement' => 'MS',    'requires_supervision' => false, 'can_prescribe' => false, 'is_independent' => true,  'scope_notes' => 'Communication, swallowing, cognitive-linguistic disorders.', 'sort_order' => 54],
            ['slug' => 'aud',    'abbreviation' => 'AuD',      'name' => 'Audiologist',                                 'discipline' => 'therapy',        'education_requirement' => 'AuD',   'requires_supervision' => false, 'can_prescribe' => false, 'is_independent' => true,  'scope_notes' => 'Hearing and balance evaluation, hearing aids, cochlear implants.', 'sort_order' => 55],
            ['slug' => 'rt',     'abbreviation' => 'RT/RRT',   'name' => 'Respiratory Therapist',                       'discipline' => 'therapy',        'education_requirement' => 'AAS/BS', 'requires_supervision' => true, 'can_prescribe' => false, 'is_independent' => false, 'scope_notes' => 'Respiratory care, ventilator management, pulmonary rehab.', 'sort_order' => 56],

            // Dental
            ['slug' => 'dds',    'abbreviation' => 'DDS/DMD',  'name' => 'Doctor of Dental Surgery / Medicine',         'discipline' => 'dental',         'education_requirement' => 'DDS/DMD', 'requires_supervision' => false, 'can_prescribe' => true, 'is_independent' => true, 'scope_notes' => 'Full dental practice authority. Equivalent degrees.', 'sort_order' => 60],
            ['slug' => 'rdh',    'abbreviation' => 'RDH',      'name' => 'Registered Dental Hygienist',                 'discipline' => 'dental',         'education_requirement' => 'AAS/BS', 'requires_supervision' => true, 'can_prescribe' => false, 'is_independent' => false, 'scope_notes' => 'Preventive dental care, cleanings, patient education.', 'sort_order' => 61],

            // Pharmacy
            ['slug' => 'pharmd', 'abbreviation' => 'PharmD',   'name' => 'Doctor of Pharmacy',                          'discipline' => 'pharmacy',       'education_requirement' => 'PharmD', 'requires_supervision' => false, 'can_prescribe' => false, 'is_independent' => true, 'scope_notes' => 'Medication therapy management, dispensing, clinical pharmacy. Collaborative practice in some states.', 'sort_order' => 65],
            ['slug' => 'rph',    'abbreviation' => 'RPh',      'name' => 'Registered Pharmacist',                       'discipline' => 'pharmacy',       'education_requirement' => 'PharmD/BS', 'requires_supervision' => false, 'can_prescribe' => false, 'is_independent' => true, 'scope_notes' => 'Licensed pharmacist. PharmD now required for new licensees.', 'sort_order' => 66],

            // Optometry
            ['slug' => 'od',     'abbreviation' => 'OD',       'name' => 'Doctor of Optometry',                         'discipline' => 'allied_health',  'education_requirement' => 'OD',    'requires_supervision' => false, 'can_prescribe' => true,  'is_independent' => true,  'scope_notes' => 'Eye exams, vision correction, ocular disease management. Scope varies by state.', 'sort_order' => 70],

            // Chiropractic
            ['slug' => 'dc',     'abbreviation' => 'DC',       'name' => 'Doctor of Chiropractic',                      'discipline' => 'allied_health',  'education_requirement' => 'DC',    'requires_supervision' => false, 'can_prescribe' => false, 'is_independent' => true,  'scope_notes' => 'Musculoskeletal care, spinal manipulation, rehabilitation.', 'sort_order' => 75],

            // Allied Health
            ['slug' => 'rd',     'abbreviation' => 'RD/RDN',   'name' => 'Registered Dietitian / Nutritionist',         'discipline' => 'allied_health',  'education_requirement' => 'MS',    'requires_supervision' => false, 'can_prescribe' => false, 'is_independent' => true,  'scope_notes' => 'Medical nutrition therapy, dietary counseling, nutrition assessment.', 'sort_order' => 80],
            ['slug' => 'bcba',   'abbreviation' => 'BCBA',     'name' => 'Board Certified Behavior Analyst',            'discipline' => 'allied_health',  'education_requirement' => 'MA/MS', 'requires_supervision' => false, 'can_prescribe' => false, 'is_independent' => true,  'scope_notes' => 'Applied behavior analysis, autism spectrum interventions.', 'sort_order' => 81],
            ['slug' => 'emt',    'abbreviation' => 'EMT-P',    'name' => 'Paramedic',                                   'discipline' => 'allied_health',  'education_requirement' => 'Certificate', 'requires_supervision' => true, 'can_prescribe' => false, 'is_independent' => false, 'scope_notes' => 'Emergency medical services, advanced life support.', 'sort_order' => 82],
            ['slug' => 'cps',    'abbreviation' => 'CPS',      'name' => 'Certified Peer Specialist',                   'discipline' => 'allied_health',  'education_requirement' => 'Certificate', 'requires_supervision' => true, 'can_prescribe' => false, 'is_independent' => false, 'scope_notes' => 'Peer support services for behavioral health recovery. State-certified.', 'sort_order' => 83],
            ['slug' => 'chw',    'abbreviation' => 'CHW',      'name' => 'Community Health Worker',                     'discipline' => 'allied_health',  'education_requirement' => 'Certificate', 'requires_supervision' => true, 'can_prescribe' => false, 'is_independent' => false, 'scope_notes' => 'Community outreach, health education, patient navigation.', 'sort_order' => 84],
        ];

        foreach ($types as $type) {
            DB::table('license_types')->updateOrInsert(
                ['slug' => $type['slug']],
                $type
            );
        }
    }
}
