<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PayerSeeder extends Seeder
{
    /**
     * Seed the payers table with the full Credentik payer catalog.
     *
     * 63 payers total: Big 5 nationals + managed care + BCBS affiliates + regionals.
     * Each record includes enriched credentialing contact info, logo slugs, and notes.
     */
    public function run(): void
    {
        $payers = [
            // ── NATIONAL — BIG 5 ──
            [
                'slug'              => 'pyr_uhc',
                'name'              => 'UnitedHealthcare',
                'short_name'        => 'UHC',
                'category'          => 'national',
                'region'            => 'national',
                'parent_org'        => 'UnitedHealth Group',
                'stedi_id'          => '87726',
                'states'            => json_encode(['ALL']),
                'avg_cred_days'     => 90,
                'credentialing_url' => 'https://www.uhcprovider.com',
                'cred_phone'        => '(877) 842-3210',
                'cred_email'        => 'provider_credentialing@uhc.com',
                'logo_slug'         => 'unitedhealth',
                'notes'             => 'Uses CAQH ProView for credentialing. Behavioral health credentialed through Optum. Allow 90 days for initial credentialing; revalidation every 3 years.',
            ],
            [
                'slug'              => 'pyr_aetna',
                'name'              => 'Aetna',
                'short_name'        => 'Aetna',
                'category'          => 'national',
                'region'            => 'national',
                'parent_org'        => 'CVS Health',
                'stedi_id'          => '60054',
                'states'            => json_encode(['ALL']),
                'avg_cred_days'     => 75,
                'credentialing_url' => 'https://www.availity.com',
                'cred_phone'        => '(800) 624-0756',
                'cred_email'        => 'credentialing@aetna.com',
                'logo_slug'         => 'aetna',
                'notes'             => 'Submit via Availity portal. CAQH ProView data required. CVS Health merger streamlined BH credentialing. Recredentialing every 36 months.',
            ],
            [
                'slug'              => 'pyr_cigna',
                'name'              => 'Cigna',
                'short_name'        => 'Cigna',
                'category'          => 'national',
                'region'            => 'national',
                'parent_org'        => 'The Cigna Group / Evernorth',
                'stedi_id'          => '62308',
                'states'            => json_encode(['ALL']),
                'avg_cred_days'     => 60,
                'credentialing_url' => 'https://cignaforhcp.cigna.com',
                'cred_phone'        => '(800) 882-4462',
                'cred_email'        => 'provider.credentialing@cigna.com',
                'logo_slug'         => 'cigna',
                'notes'             => 'Uses CAQH ProView. Evernorth handles pharmacy/BH carve-outs. Fastest turnaround among Big 5 at ~60 days. Online status checks via CignaforHCP.',
            ],
            [
                'slug'              => 'pyr_humana',
                'name'              => 'Humana',
                'short_name'        => 'Humana',
                'category'          => 'national',
                'region'            => 'national',
                'parent_org'        => 'Humana',
                'stedi_id'          => '61101',
                'states'            => json_encode(['ALL']),
                'avg_cred_days'     => 60,
                'credentialing_url' => 'https://provider.humana.com',
                'cred_phone'        => '(800) 444-9137',
                'cred_email'        => 'providerservices@humana.com',
                'logo_slug'         => 'humana',
                'notes'             => 'Uses CAQH ProView. Strong Medicare Advantage presence. Submit applications via Availity or provider portal. Allow 60 days for processing.',
            ],
            [
                'slug'              => 'pyr_medicare',
                'name'              => 'Medicare',
                'short_name'        => 'Medicare',
                'category'          => 'national',
                'region'            => 'national',
                'parent_org'        => 'CMS',
                'stedi_id'          => 'CMS',
                'states'            => json_encode(['ALL']),
                'avg_cred_days'     => 120,
                'credentialing_url' => 'https://pecos.cms.hhs.gov',
                'cred_phone'        => '(866) 837-0241',
                'cred_email'        => null,
                'logo_slug'         => 'medicare',
                'notes'             => 'Enrollment via PECOS (Provider Enrollment, Chain, and Ownership System). CMS 855I for individual providers, 855B for groups. Revalidation every 5 years. No email support; use PECOS online or call.',
            ],
            [
                'slug'              => 'pyr_medicaid',
                'name'              => 'Medicaid',
                'short_name'        => 'Medicaid',
                'category'          => 'national',
                'region'            => 'national',
                'parent_org'        => 'CMS',
                'stedi_id'          => null,
                'states'            => json_encode(['ALL']),
                'avg_cred_days'     => 90,
                'credentialing_url' => 'https://www.medicaid.gov/provider-enrollment',
                'cred_phone'        => '(877) 267-2323',
                'cred_email'        => null,
                'logo_slug'         => 'medicaid',
                'notes'             => 'Each state administers its own Medicaid program. Enroll in each state individually through state Medicaid portal. Must have active Medicare enrollment (CMS 855) in most states before Medicaid enrollment.',
            ],

            // ── NATIONAL — MANAGED CARE / ACA ──
            [
                'slug'              => 'pyr_centene',
                'name'              => 'Centene/Ambetter',
                'short_name'        => 'Centene',
                'category'          => 'national',
                'region'            => 'national',
                'parent_org'        => 'Centene Corporation',
                'stedi_id'          => 'AMB01',
                'states'            => json_encode(['ALL']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 575-2091',
                'cred_email'        => 'credentialing@centene.com',
                'logo_slug'         => 'centene',
                'notes'             => 'Operates Ambetter (ACA marketplace), WellCare (Medicare/Medicaid), Sunshine Health (FL), Superior (TX). Credentialing handled by subsidiary plan in each state. Uses CAQH ProView.',
            ],
            [
                'slug'              => 'pyr_molina',
                'name'              => 'Molina Healthcare',
                'short_name'        => 'Molina',
                'category'          => 'national',
                'region'            => 'national',
                'parent_org'        => 'Molina Healthcare',
                'stedi_id'          => 'MOLIN',
                'states'            => json_encode(['ALL']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
                'cred_phone'        => '(888) 562-5442',
                'cred_email'        => 'provider.services@molinahealthcare.com',
                'logo_slug'         => 'molina',
                'notes'             => 'Focus on Medicaid/ACA managed care. Uses CAQH ProView. State-specific applications may be required. Relatively fast turnaround at 45 days.',
            ],
            [
                'slug'              => 'pyr_oscar',
                'name'              => 'Oscar Health',
                'short_name'        => 'Oscar',
                'category'          => 'national',
                'region'            => 'national',
                'parent_org'        => 'Oscar Health',
                'stedi_id'          => 'OSCAR',
                'states'            => json_encode(['ALL']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
                'cred_phone'        => '(855) 672-2755',
                'cred_email'        => 'provider.network@hioscar.com',
                'logo_slug'         => 'oscar',
                'notes'             => 'ACA marketplace plan with tech-forward approach. Submit credentialing via CAQH ProView. Limited geographic presence; growing rapidly. Quick ~45 day turnaround.',
            ],
            [
                'slug'              => 'pyr_tricare',
                'name'              => 'Tricare',
                'short_name'        => 'TRICARE',
                'category'          => 'national',
                'region'            => 'national',
                'parent_org'        => 'DoD / DHA',
                'stedi_id'          => 'TRIC',
                'states'            => json_encode(['ALL']),
                'avg_cred_days'     => 90,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 874-2273',
                'cred_email'        => 'provider.relations@tricare.mil',
                'logo_slug'         => 'tricare',
                'notes'             => 'Military health system managed by DHA. Credentialing through regional contractors (Health Net Federal, Humana Military). Must be enrolled in TRICARE network via contractor portal.',
            ],
            [
                'slug'              => 'pyr_kaiser',
                'name'              => 'Kaiser Permanente',
                'short_name'        => 'Kaiser',
                'category'          => 'national',
                'region'            => 'west',
                'parent_org'        => 'Kaiser Foundation',
                'stedi_id'          => null,
                'states'            => json_encode(['CA', 'CO', 'GA', 'HI', 'MD', 'OR', 'VA', 'WA', 'DC']),
                'avg_cred_days'     => 90,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 390-3510',
                'cred_email'        => 'credentialing@kp.org',
                'logo_slug'         => 'kaiser',
                'notes'             => 'Integrated care model with limited external provider network. Credentialing for outside providers is selective. Apply through regional Kaiser office. Uses internal credentialing system, not CAQH.',
            ],

            // ── BCBS — ANTHEM/ELEVANCE ──
            [
                'slug'              => 'pyr_anthem',
                'name'              => 'Anthem/Elevance',
                'short_name'        => 'Anthem',
                'category'          => 'bcbs_anthem',
                'region'            => 'national',
                'parent_org'        => 'Elevance Health',
                'stedi_id'          => null,
                'states'            => json_encode(['CA', 'CO', 'CT', 'GA', 'IN', 'KY', 'ME', 'MO', 'NV', 'NH', 'NY', 'OH', 'VA', 'WI']),
                'avg_cred_days'     => 90,
                'credentialing_url' => 'https://www.availity.com',
                'cred_phone'        => '(800) 677-6669',
                'cred_email'        => 'provider.credentialing@anthem.com',
                'logo_slug'         => 'anthem',
                'notes'             => 'Submit via Availity portal. Uses CAQH ProView. Largest BCBS licensee operating as Elevance Health. State-specific requirements may vary. Recredentialing every 3 years.',
            ],

            // ── BCBS — HCSC ──
            [
                'slug'              => 'pyr_hcsc',
                'name'              => 'HCSC',
                'short_name'        => 'HCSC',
                'category'          => 'bcbs_hcsc',
                'region'            => 'midwest',
                'parent_org'        => 'Health Care Service Corporation',
                'stedi_id'          => null,
                'states'            => json_encode(['TX', 'IL', 'OK', 'NM', 'MT']),
                'avg_cred_days'     => 90,
                'credentialing_url' => 'https://www.bcbsil.com/provider',
                'cred_phone'        => '(800) 972-8088',
                'cred_email'        => 'provider.credentialing@hcsc.net',
                'logo_slug'         => 'hcsc',
                'notes'             => 'Largest customer-owned health insurer in the US. Operates BCBS plans in TX, IL, OK, NM, MT. Uses CAQH ProView. Submit through Availity or state-specific BCBS portal.',
            ],
            [
                'slug'              => 'pyr_bcbs_il',
                'name'              => 'BCBS of Illinois',
                'short_name'        => 'BCBS IL',
                'category'          => 'bcbs_hcsc',
                'region'            => 'midwest',
                'parent_org'        => 'Health Care Service Corporation',
                'stedi_id'          => null,
                'states'            => json_encode(['IL']),
                'avg_cred_days'     => 90,
                'credentialing_url' => 'https://www.bcbsil.com/provider',
                'cred_phone'        => '(800) 972-8088',
                'cred_email'        => 'provider.services@bcbsil.com',
                'logo_slug'         => 'bcbs',
                'notes'             => 'Operated by HCSC. Uses CAQH ProView. Submit via Availity portal. State-specific credentialing requirements for IL. Recredentialing every 36 months.',
            ],
            [
                'slug'              => 'pyr_bcbs_tx',
                'name'              => 'BCBS of Texas',
                'short_name'        => 'BCBS TX',
                'category'          => 'bcbs_hcsc',
                'region'            => 'south',
                'parent_org'        => 'Health Care Service Corporation',
                'stedi_id'          => null,
                'states'            => json_encode(['TX']),
                'avg_cred_days'     => 90,
                'credentialing_url' => 'https://www.bcbstx.com/provider',
                'cred_phone'        => '(800) 451-0287',
                'cred_email'        => 'provider.services@bcbstx.com',
                'logo_slug'         => 'bcbs',
                'notes'             => 'Operated by HCSC. Largest BCBS plan by enrollment in TX. Uses CAQH ProView. Submit via Availity. TX-specific credentialing timelines may apply.',
            ],

            // ── BCBS — HIGHMARK ──
            [
                'slug'              => 'pyr_highmark',
                'name'              => 'Highmark BCBS',
                'short_name'        => 'Highmark',
                'category'          => 'bcbs_highmark',
                'region'            => 'northeast',
                'parent_org'        => 'Highmark Health',
                'stedi_id'          => null,
                'states'            => json_encode(['PA', 'DE', 'WV', 'NY']),
                'avg_cred_days'     => 75,
                'credentialing_url' => 'https://www.availity.com',
                'cred_phone'        => '(800) 547-3627',
                'cred_email'        => 'provider.credentialing@highmark.com',
                'logo_slug'         => 'highmark',
                'notes'             => 'Submit via Availity portal. Uses CAQH ProView. Operates in PA, DE, WV, and western NY. Also operates Allegheny Health Network. Recredentialing every 3 years.',
            ],

            // ── BCBS — PREMERA / REGENCE ──
            [
                'slug'              => 'pyr_premera',
                'name'              => 'Premera Blue Cross',
                'short_name'        => 'Premera',
                'category'          => 'bcbs_independent',
                'region'            => 'pacific_nw',
                'parent_org'        => 'Premera',
                'stedi_id'          => null,
                'states'            => json_encode(['WA', 'AK']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 722-1471',
                'cred_email'        => 'credentialing@premera.com',
                'logo_slug'         => 'premera',
                'notes'             => 'Largest BCBS plan in the Pacific NW. Uses CAQH ProView. WA and AK provider enrollment. Behavioral health credentialed separately. Allow 60 days for processing.',
            ],
            [
                'slug'              => 'pyr_regence',
                'name'              => 'Regence BlueShield',
                'short_name'        => 'Regence',
                'category'          => 'bcbs_independent',
                'region'            => 'pacific_nw',
                'parent_org'        => 'Cambia Health Solutions',
                'stedi_id'          => null,
                'states'            => json_encode(['WA', 'OR', 'UT', 'ID']),
                'avg_cred_days'     => 60,
                'credentialing_url' => 'https://www.availity.com',
                'cred_phone'        => '(800) 452-7278',
                'cred_email'        => 'provider.relations@regence.com',
                'logo_slug'         => 'regence',
                'notes'             => 'Submit via Availity portal. Part of Cambia Health Solutions. Operates in WA, OR, UT, ID. Uses CAQH ProView. State-specific forms may be required.',
            ],

            // ── BCBS — INDEPENDENT STATE PLANS ──
            [
                'slug'              => 'pyr_florida_blue',
                'name'              => 'Florida Blue',
                'short_name'        => 'FL Blue',
                'category'          => 'bcbs_independent',
                'region'            => 'southeast',
                'parent_org'        => 'GuideWell',
                'stedi_id'          => null,
                'states'            => json_encode(['FL']),
                'avg_cred_days'     => 60,
                'credentialing_url' => 'https://www.availity.com',
                'cred_phone'        => '(800) 727-2227',
                'cred_email'        => 'provider.credentialing@floridablue.com',
                'logo_slug'         => 'florida_blue',
                'notes'             => 'Submit via Availity portal. Uses CAQH ProView. Largest insurer in FL. Part of GuideWell family. Behavioral health credentialed through New Directions.',
            ],
            [
                'slug'              => 'pyr_bcbs_ga',
                'name'              => 'BCBS of Georgia',
                'short_name'        => 'BCBS GA',
                'category'          => 'bcbs_independent',
                'region'            => 'southeast',
                'parent_org'        => 'Anthem/Elevance Health',
                'stedi_id'          => null,
                'states'            => json_encode(['GA']),
                'avg_cred_days'     => 75,
                'credentialing_url' => 'https://www.availity.com',
                'cred_phone'        => '(800) 436-3916',
                'cred_email'        => 'provider.services@bcbsga.com',
                'logo_slug'         => 'bcbs',
                'notes'             => 'Operated under Anthem/Elevance Health umbrella. Submit via Availity. Uses CAQH ProView. GA-specific credentialing requirements apply. Recredentialing every 36 months.',
            ],
            [
                'slug'              => 'pyr_carefirst',
                'name'              => 'CareFirst BCBS',
                'short_name'        => 'CareFirst',
                'category'          => 'bcbs_independent',
                'region'            => 'northeast',
                'parent_org'        => 'CareFirst',
                'stedi_id'          => null,
                'states'            => json_encode(['MD', 'DC', 'VA']),
                'avg_cred_days'     => 60,
                'credentialing_url' => 'https://provider.carefirst.com',
                'cred_phone'        => '(800) 842-5975',
                'cred_email'        => 'provider.credentialing@carefirst.com',
                'logo_slug'         => 'carefirst',
                'notes'             => 'Serves MD, DC, and northern VA. Uses CAQH ProView. Submit through CareFirst provider portal. Behavioral health through Magellan. Recredentialing every 3 years.',
            ],
            [
                'slug'              => 'pyr_bcbs_ma',
                'name'              => 'BCBS of Massachusetts',
                'short_name'        => 'BCBS MA',
                'category'          => 'bcbs_independent',
                'region'            => 'northeast',
                'parent_org'        => 'BCBS MA',
                'stedi_id'          => null,
                'states'            => json_encode(['MA']),
                'avg_cred_days'     => 60,
                'credentialing_url' => 'https://provider.bluecrossma.com',
                'cred_phone'        => '(800) 882-2060',
                'cred_email'        => 'provider.enrollment@bcbsma.com',
                'logo_slug'         => 'bcbs',
                'notes'             => 'Largest insurer in MA. Uses CAQH ProView. Submit through provider portal. Strong telehealth credentialing program. Recredentialing every 36 months.',
            ],
            [
                'slug'              => 'pyr_bcbs_az',
                'name'              => 'BCBS of Arizona',
                'short_name'        => 'BCBS AZ',
                'category'          => 'bcbs_independent',
                'region'            => 'west',
                'parent_org'        => 'BCBS AZ',
                'stedi_id'          => null,
                'states'            => json_encode(['AZ']),
                'avg_cred_days'     => 60,
                'credentialing_url' => 'https://credentialing.azblue.com',
                'cred_phone'        => '(800) 232-2345',
                'cred_email'        => 'credentialing@azblue.com',
                'logo_slug'         => 'bcbs',
                'notes'             => 'Uses CAQH ProView. Submit via dedicated credentialing portal. AZ-specific requirements may apply. Fast 60-day turnaround. Recredentialing every 3 years.',
            ],
            [
                'slug'              => 'pyr_horizon',
                'name'              => 'Horizon BCBS',
                'short_name'        => 'Horizon',
                'category'          => 'bcbs_independent',
                'region'            => 'northeast',
                'parent_org'        => 'Horizon',
                'stedi_id'          => null,
                'states'            => json_encode(['NJ']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 355-2583',
                'cred_email'        => 'provider.credentialing@horizonblue.com',
                'logo_slug'         => 'horizon',
                'notes'             => 'Largest insurer in NJ. Uses CAQH ProView. Submit through NaviNet provider portal. Behavioral health through Horizon Behavioral Health. Recredentialing every 36 months.',
            ],
            [
                'slug'              => 'pyr_bcbs_nc',
                'name'              => 'BCBS of North Carolina',
                'short_name'        => 'BCBS NC',
                'category'          => 'bcbs_independent',
                'region'            => 'southeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['NC']),
                'avg_cred_days'     => 75,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 214-4844',
                'cred_email'        => 'provider.enrollment@bcbsnc.com',
                'logo_slug'         => 'bcbs',
                'notes'             => 'Uses CAQH ProView. Dominant insurer in NC. Credentialing takes slightly longer at 75 days. Behavioral health through Magellan. Submit through Blue eSM portal.',
            ],
            [
                'slug'              => 'pyr_bcbs_sc',
                'name'              => 'BCBS of South Carolina',
                'short_name'        => 'BCBS SC',
                'category'          => 'bcbs_independent',
                'region'            => 'southeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['SC']),
                'avg_cred_days'     => 75,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 868-2528',
                'cred_email'        => 'credentialing@bcbssc.com',
                'logo_slug'         => 'bcbs',
                'notes'             => 'Uses CAQH ProView. Dominant insurer in SC. Submit through My Insurance Manager portal. Allow 75 days for initial processing. Recredentialing every 3 years.',
            ],
            [
                'slug'              => 'pyr_bcbs_tn',
                'name'              => 'BCBS of Tennessee',
                'short_name'        => 'BCBS TN',
                'category'          => 'bcbs_independent',
                'region'            => 'southeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['TN']),
                'avg_cred_days'     => 75,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 565-9140',
                'cred_email'        => 'provider.credentialing@bcbst.com',
                'logo_slug'         => 'bcbs',
                'notes'             => 'Uses CAQH ProView. Dominant payer in TN market. Submit via Availity. Behavioral health through BCBST internal team. Recredentialing every 36 months.',
            ],
            [
                'slug'              => 'pyr_bcbs_al',
                'name'              => 'BCBS of Alabama',
                'short_name'        => 'BCBS AL',
                'category'          => 'bcbs_independent',
                'region'            => 'southeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['AL']),
                'avg_cred_days'     => 75,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 248-7178',
                'cred_email'        => 'credentialing@bcbsal.org',
                'logo_slug'         => 'bcbs',
                'notes'             => 'Uses CAQH ProView. Largest insurer in AL covering ~90% of market. Submit through provider portal. Allow 75 days. Recredentialing every 3 years.',
            ],
            [
                'slug'              => 'pyr_bcbs_mi',
                'name'              => 'BCBS of Michigan',
                'short_name'        => 'BCBS MI',
                'category'          => 'bcbs_independent',
                'region'            => 'midwest',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['MI']),
                'avg_cred_days'     => 75,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 822-2761',
                'cred_email'        => 'provider.enrollment@bcbsm.com',
                'logo_slug'         => 'bcbs',
                'notes'             => 'Uses CAQH ProView. Largest insurer in MI. Submit through web-DENIS provider portal. BH credentialed through BCBSM behavioral health team. Recredentialing every 36 months.',
            ],
            [
                'slug'              => 'pyr_bcbs_mn',
                'name'              => 'BCBS of Minnesota',
                'short_name'        => 'BCBS MN',
                'category'          => 'bcbs_independent',
                'region'            => 'midwest',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['MN']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 262-0820',
                'cred_email'        => 'provider.credentialing@bluecrossmn.com',
                'logo_slug'         => 'bcbs',
                'notes'             => 'Uses CAQH ProView. Submit via Availity portal. Fast 60-day turnaround. Strong presence in MN individual/group market. Recredentialing every 3 years.',
            ],
            [
                'slug'              => 'pyr_bcbs_la',
                'name'              => 'BCBS of Louisiana',
                'short_name'        => 'BCBS LA',
                'category'          => 'bcbs_independent',
                'region'            => 'south',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['LA']),
                'avg_cred_days'     => 75,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 716-2299',
                'cred_email'        => 'credentialing@bcbsla.com',
                'logo_slug'         => 'bcbs',
                'notes'             => 'Uses CAQH ProView. Dominant insurer in LA. Submit through iLinkBlue provider portal. Allow 75 days for processing. Behavioral health credentialed internally.',
            ],
            [
                'slug'              => 'pyr_bcbs_ks',
                'name'              => 'BCBS of Kansas',
                'short_name'        => 'BCBS KS',
                'category'          => 'bcbs_independent',
                'region'            => 'midwest',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['KS']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 432-3587',
                'cred_email'        => 'provider.relations@bcbsks.com',
                'logo_slug'         => 'bcbs',
                'notes'             => 'Uses CAQH ProView. Dominant payer in KS market. 60-day processing time. Submit through Availity portal. Recredentialing every 36 months.',
            ],
            [
                'slug'              => 'pyr_wellmark',
                'name'              => 'Wellmark BCBS',
                'short_name'        => 'Wellmark',
                'category'          => 'bcbs_independent',
                'region'            => 'midwest',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['IA', 'SD']),
                'avg_cred_days'     => 60,
                'credentialing_url' => 'https://www.wellmark.com/e-cred/index.aspx',
                'cred_phone'        => '(800) 524-9242',
                'cred_email'        => 'credentialing@wellmark.com',
                'logo_slug'         => 'wellmark',
                'notes'             => 'Uses dedicated e-Cred online credentialing system (not CAQH). Dominant insurer in IA and SD. Submit via Wellmark e-Cred portal. 60-day processing. Recredentialing every 3 years.',
            ],
            [
                'slug'              => 'pyr_independence',
                'name'              => 'Independence Blue Cross',
                'short_name'        => 'IBX',
                'category'          => 'bcbs_independent',
                'region'            => 'northeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['PA']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 275-2583',
                'cred_email'        => 'provider.credentialing@ibx.com',
                'logo_slug'         => 'independence',
                'notes'             => 'Dominant insurer in southeastern PA/Philadelphia area. Uses CAQH ProView. Submit through NaviNet provider portal. 60-day turnaround. Recredentialing every 36 months.',
            ],

            // ── REGIONAL — NORTHEAST ──
            [
                'slug'              => 'pyr_emblem',
                'name'              => 'EmblemHealth',
                'short_name'        => 'Emblem',
                'category'          => 'regional',
                'region'            => 'northeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['NY']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
                'cred_phone'        => '(877) 842-3625',
                'cred_email'        => 'provider.relations@emblemhealth.com',
                'logo_slug'         => 'emblemhealth',
                'notes'             => 'Major NY metro area plan (GHI + HIP merger). Uses CAQH ProView. Submit via provider portal or fax. Behavioral health credentialed through EmblemHealth BH team.',
            ],
            [
                'slug'              => 'pyr_fidelis',
                'name'              => 'Fidelis Care',
                'short_name'        => 'Fidelis',
                'category'          => 'regional',
                'region'            => 'northeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['NY']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
                'cred_phone'        => '(888) 343-3547',
                'cred_email'        => 'credentialing@fideliscare.org',
                'logo_slug'         => 'fidelis',
                'notes'             => 'NY Medicaid managed care plan. Uses CAQH ProView. Fast 45-day turnaround. Strong Medicaid/CHIP presence. Submit through provider portal.',
            ],
            [
                'slug'              => 'pyr_healthfirst',
                'name'              => 'Healthfirst',
                'short_name'        => 'Healthfirst',
                'category'          => 'regional',
                'region'            => 'northeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['NY']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
                'cred_phone'        => '(888) 801-4247',
                'cred_email'        => 'provider.services@healthfirst.org',
                'logo_slug'         => 'healthfirst',
                'notes'             => 'NYC-area managed care plan. Uses CAQH ProView. Strong Medicaid and Medicare managed care presence. Submit through provider enrollment portal.',
            ],
            [
                'slug'              => 'pyr_connecticare',
                'name'              => 'ConnectiCare',
                'short_name'        => 'ConnectiCare',
                'category'          => 'regional',
                'region'            => 'northeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['CT']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 251-7722',
                'cred_email'        => 'provider.relations@connecticare.com',
                'logo_slug'         => 'connecticare',
                'notes'             => 'CT-based health plan. Uses CAQH ProView. Fast 45-day processing. Submit via fax or provider portal. Recredentialing every 3 years.',
            ],
            [
                'slug'              => 'pyr_harvard_pilgrim',
                'name'              => 'Harvard Pilgrim',
                'short_name'        => 'HPHC',
                'category'          => 'regional',
                'region'            => 'northeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['MA', 'NH', 'ME', 'CT']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
                'cred_phone'        => '(888) 333-4742',
                'cred_email'        => 'provider.credentialing@harvardpilgrim.org',
                'logo_slug'         => 'harvard_pilgrim',
                'notes'             => 'New England regional plan (now part of Point32Health with Tufts). Uses CAQH ProView. Submit through provider portal. 60-day processing.',
            ],
            [
                'slug'              => 'pyr_tufts',
                'name'              => 'Tufts Health Plan',
                'short_name'        => 'Tufts',
                'category'          => 'regional',
                'region'            => 'northeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['MA']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 462-0224',
                'cred_email'        => 'provider.credentialing@tufts-health.com',
                'logo_slug'         => 'tufts',
                'notes'             => 'MA-based plan (now part of Point32Health with Harvard Pilgrim). Uses CAQH ProView. Submit via provider portal. 60-day turnaround.',
            ],
            [
                'slug'              => 'pyr_mvp',
                'name'              => 'MVP Health Care',
                'short_name'        => 'MVP',
                'category'          => 'regional',
                'region'            => 'northeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['NY', 'VT']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 684-9286',
                'cred_email'        => 'provider.relations@mvphealthcare.com',
                'logo_slug'         => 'mvp',
                'notes'             => 'Upstate NY and VT regional plan. Uses CAQH ProView. Submit through provider portal. 60-day processing time. Recredentialing every 3 years.',
            ],
            [
                'slug'              => 'pyr_amerihealth',
                'name'              => 'AmeriHealth',
                'short_name'        => 'AmeriHealth',
                'category'          => 'regional',
                'region'            => 'northeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['PA', 'NJ', 'DE']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 454-3730',
                'cred_email'        => 'provider.services@amerihealth.com',
                'logo_slug'         => 'amerihealth',
                'notes'             => 'Serves PA, NJ, DE region. Uses CAQH ProView. Submit through NaviNet provider portal. 60-day turnaround. Part of Independence Health Group.',
            ],
            [
                'slug'              => 'pyr_upmc',
                'name'              => 'UPMC Health Plan',
                'short_name'        => 'UPMC',
                'category'          => 'regional',
                'region'            => 'northeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['PA']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
                'cred_phone'        => '(866) 918-1595',
                'cred_email'        => 'provider.credentialing@upmchp.com',
                'logo_slug'         => 'upmc',
                'notes'             => 'Western PA integrated health system plan. Uses CAQH ProView. Submit through UPMC provider portal. 60-day processing. Strong hospital network in Pittsburgh area.',
            ],

            // ── REGIONAL — SOUTHEAST ──
            [
                'slug'              => 'pyr_avmed',
                'name'              => 'AvMed',
                'short_name'        => 'AvMed',
                'category'          => 'regional',
                'region'            => 'southeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['FL']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 452-8633',
                'cred_email'        => 'credentialing@avmed.org',
                'logo_slug'         => 'avmed',
                'notes'             => 'FL-based HMO. Uses CAQH ProView. Fast 45-day processing. Submit through provider portal. Strong South FL presence.',
            ],
            [
                'slug'              => 'pyr_simply',
                'name'              => 'Simply Healthcare',
                'short_name'        => 'Simply',
                'category'          => 'regional',
                'region'            => 'southeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['FL']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
                'cred_phone'        => '(877) 747-6759',
                'cred_email'        => 'provider.services@simplyhealthcareplans.com',
                'logo_slug'         => 'simply',
                'notes'             => 'FL Medicaid managed care plan. Uses CAQH ProView. Fast 45-day turnaround. Strong Medicaid and Medicare presence in FL. Submit via provider portal.',
            ],
            [
                'slug'              => 'pyr_sunshine',
                'name'              => 'Sunshine Health',
                'short_name'        => 'Sunshine',
                'category'          => 'regional',
                'region'            => 'southeast',
                'parent_org'        => 'Centene',
                'stedi_id'          => null,
                'states'            => json_encode(['FL']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
                'cred_phone'        => '(866) 796-0530',
                'cred_email'        => 'credentialing@sunshinestatehealth.com',
                'logo_slug'         => 'sunshine',
                'notes'             => 'Centene subsidiary for FL Medicaid managed care. Uses CAQH ProView. 45-day processing. Submit through Sunshine Health provider portal or Availity.',
            ],
            [
                'slug'              => 'pyr_optima',
                'name'              => 'Optima Health',
                'short_name'        => 'Optima',
                'category'          => 'regional',
                'region'            => 'southeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['VA']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 881-4021',
                'cred_email'        => 'provider.relations@optimahealth.com',
                'logo_slug'         => 'optima',
                'notes'             => 'VA-based plan affiliated with Sentara Healthcare. Uses CAQH ProView. 45-day processing. Submit through provider portal. Strong Hampton Roads/Tidewater presence.',
            ],
            [
                'slug'              => 'pyr_virginia_premier',
                'name'              => 'Virginia Premier',
                'short_name'        => 'VA Premier',
                'category'          => 'regional',
                'region'            => 'southeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['VA']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 727-7536',
                'cred_email'        => 'credentialing@vapremier.com',
                'logo_slug'         => 'virginia_premier',
                'notes'             => 'VA Medicaid managed care plan. Uses CAQH ProView. 45-day turnaround. Affiliated with VCU Health System. Submit through provider portal.',
            ],
            [
                'slug'              => 'pyr_priority_partners',
                'name'              => 'Priority Partners',
                'short_name'        => 'Priority',
                'category'          => 'regional',
                'region'            => 'northeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['MD']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 654-9728',
                'cred_email'        => 'credentialing@jhhc.com',
                'logo_slug'         => 'priority_partners',
                'notes'             => 'MD Medicaid managed care (Johns Hopkins HealthCare). Uses CAQH ProView. 45-day processing. Submit through provider portal. Strong Baltimore area network.',
            ],
            [
                'slug'              => 'pyr_wellcare',
                'name'              => 'WellCare',
                'short_name'        => 'WellCare',
                'category'          => 'regional',
                'region'            => 'southeast',
                'parent_org'        => 'Centene',
                'stedi_id'          => null,
                'states'            => json_encode(['FL', 'GA', 'KY', 'NY', 'TX']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
                'cred_phone'        => '(866) 530-9491',
                'cred_email'        => 'provider.credentialing@wellcare.com',
                'logo_slug'         => 'wellcare',
                'notes'             => 'Centene subsidiary focused on Medicare Advantage and Medicaid. Uses CAQH ProView. 60-day processing. Submit through WellCare provider portal. Multi-state presence.',
            ],

            // ── REGIONAL — MIDWEST ──
            [
                'slug'              => 'pyr_caresource',
                'name'              => 'CareSource',
                'short_name'        => 'CareSource',
                'category'          => 'regional',
                'region'            => 'midwest',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['OH', 'IN', 'GA', 'KY', 'WV']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 488-0134',
                'cred_email'        => 'credentialing@caresource.com',
                'logo_slug'         => 'caresource',
                'notes'             => 'Nonprofit Medicaid/ACA managed care plan. Uses CAQH ProView. Fast 45-day turnaround. Strong OH/Midwest Medicaid presence. Submit through provider portal.',
            ],
            [
                'slug'              => 'pyr_medical_mutual',
                'name'              => 'Medical Mutual',
                'short_name'        => 'Med Mutual',
                'category'          => 'regional',
                'region'            => 'midwest',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['OH']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 382-5729',
                'cred_email'        => 'provider.services@medmutual.com',
                'logo_slug'         => 'medical_mutual',
                'notes'             => 'OH-based commercial health plan. Uses CAQH ProView. 60-day processing. Submit through provider portal. Largest OH-based health insurer.',
            ],
            [
                'slug'              => 'pyr_priority_health',
                'name'              => 'Priority Health',
                'short_name'        => 'Priority Health',
                'category'          => 'regional',
                'region'            => 'midwest',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['MI']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 956-1954',
                'cred_email'        => 'provider.credentialing@priorityhealth.com',
                'logo_slug'         => 'priority_health',
                'notes'             => 'MI-based plan affiliated with Spectrum Health. Uses CAQH ProView. 60-day processing. Submit through provider portal. Strong West MI presence.',
            ],
            [
                'slug'              => 'pyr_healthpartners',
                'name'              => 'HealthPartners',
                'short_name'        => 'HealthPartners',
                'category'          => 'regional',
                'region'            => 'midwest',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['MN', 'WI']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 883-2177',
                'cred_email'        => 'provider.relations@healthpartners.com',
                'logo_slug'         => 'healthpartners',
                'notes'             => 'MN/WI integrated health system and plan. Uses CAQH ProView. 60-day processing. Submit through provider portal. Consumer-governed nonprofit.',
            ],

            // ── REGIONAL — WEST / MOUNTAIN ──
            [
                'slug'              => 'pyr_hpn',
                'name'              => 'Health Plan of Nevada',
                'short_name'        => 'HPN',
                'category'          => 'regional',
                'region'            => 'west',
                'parent_org'        => 'UnitedHealth Group',
                'stedi_id'          => null,
                'states'            => json_encode(['NV']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 777-1840',
                'cred_email'        => 'provider.credentialing@hpnv.com',
                'logo_slug'         => 'hpn',
                'notes'             => 'NV-based plan owned by UnitedHealth Group. Uses CAQH ProView. 60-day processing. Submit through UHC provider portal. Largest commercial HMO in NV.',
            ],
            [
                'slug'              => 'pyr_mercy_care',
                'name'              => 'Mercy Care',
                'short_name'        => 'Mercy Care',
                'category'          => 'regional',
                'region'            => 'west',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['AZ']),
                'avg_cred_days'     => 45,
                'credentialing_url' => 'https://www.availity.com',
                'cred_phone'        => '(800) 624-3879',
                'cred_email'        => 'credentialing@mercycareaz.org',
                'logo_slug'         => 'mercy_care',
                'notes'             => 'AZ Medicaid (AHCCCS) managed care plan. Submit via Availity. Uses CAQH ProView. 45-day processing. Strong Maricopa County presence.',
            ],
            [
                'slug'              => 'pyr_banner_aetna',
                'name'              => 'Banner | Aetna',
                'short_name'        => 'Banner Aetna',
                'category'          => 'regional',
                'region'            => 'west',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['AZ']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
                'cred_phone'        => '(855) 309-0400',
                'cred_email'        => 'provider.services@banneraetna.com',
                'logo_slug'         => 'banner_aetna',
                'notes'             => 'Joint venture between Banner Health and Aetna in AZ. Uses CAQH ProView. 60-day processing. Submit through provider portal. Leverages Banner hospital network.',
            ],

            // ── REGIONAL — PACIFIC NW ──
            [
                'slug'              => 'pyr_coordinated_care',
                'name'              => 'Coordinated Care',
                'short_name'        => 'Coordinated Care',
                'category'          => 'regional',
                'region'            => 'pacific_nw',
                'parent_org'        => 'Centene',
                'stedi_id'          => null,
                'states'            => json_encode(['WA']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
                'cred_phone'        => '(877) 644-4613',
                'cred_email'        => 'credentialing@coordinatedcarehealth.com',
                'logo_slug'         => 'coordinated_care',
                'notes'             => 'Centene subsidiary for WA Medicaid managed care. Uses CAQH ProView. 45-day processing. Submit through provider portal. Apple Health (Medicaid) plans.',
            ],
            [
                'slug'              => 'pyr_community_health_wa',
                'name'              => 'Community Health Plan of WA',
                'short_name'        => 'CHPW',
                'category'          => 'regional',
                'region'            => 'pacific_nw',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['WA']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 440-1561',
                'cred_email'        => 'credentialing@chpw.org',
                'logo_slug'         => 'chpw',
                'notes'             => 'WA nonprofit Medicaid managed care plan. Uses CAQH ProView. 45-day processing. Submit through provider portal. Serves Apple Health (Medicaid) members.',
            ],
            [
                'slug'              => 'pyr_providence',
                'name'              => 'Providence Health Plan',
                'short_name'        => 'Providence',
                'category'          => 'regional',
                'region'            => 'pacific_nw',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['OR', 'WA']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
                'cred_phone'        => '(800) 878-4445',
                'cred_email'        => 'provider.credentialing@providence.org',
                'logo_slug'         => 'providence',
                'notes'             => 'OR/WA plan affiliated with Providence St. Joseph Health. Uses CAQH ProView. 60-day processing. Submit through provider portal. Strong hospital network in Pacific NW.',
            ],
            [
                'slug'              => 'pyr_moda',
                'name'              => 'Moda Health',
                'short_name'        => 'Moda',
                'category'          => 'regional',
                'region'            => 'pacific_nw',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['OR', 'AK']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
                'cred_phone'        => '(877) 605-3229',
                'cred_email'        => 'provider.relations@modahealth.com',
                'logo_slug'         => 'moda',
                'notes'             => 'OR/AK-based health plan. Uses CAQH ProView. 60-day processing. Submit through provider portal. Also offers dental through Delta Dental of Oregon.',
            ],

            // ── REGIONAL — SOUTH / TX ──
            [
                'slug'              => 'pyr_superior',
                'name'              => 'Superior HealthPlan',
                'short_name'        => 'Superior',
                'category'          => 'regional',
                'region'            => 'south',
                'parent_org'        => 'Centene',
                'stedi_id'          => null,
                'states'            => json_encode(['TX']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
                'cred_phone'        => '(877) 277-9772',
                'cred_email'        => 'provider.services@superiorhealthplan.com',
                'logo_slug'         => 'superior',
                'notes'             => 'Centene subsidiary for TX Medicaid/CHIP managed care. Uses CAQH ProView. 60-day processing. Submit through provider portal. Largest Medicaid managed care plan in TX.',
            ],
            [
                'slug'              => 'pyr_healthy_blue',
                'name'              => 'Healthy Blue',
                'short_name'        => 'Healthy Blue',
                'category'          => 'regional',
                'region'            => 'south',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['LA', 'NC', 'SC']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
                'cred_phone'        => '(844) 594-5072',
                'cred_email'        => 'provider.relations@healthybluenc.com',
                'logo_slug'         => 'healthy_blue',
                'notes'             => 'Medicaid managed care plan (Anthem/BCBS partnership). Operates in LA, NC, SC. Uses CAQH ProView. 60-day processing. Submit through Availity portal.',
            ],
        ];

        // Market share percentages (2025 national estimates)
        $marketShares = [
            'pyr_uhc'               => 14.0,
            'pyr_aetna'             => 7.5,
            'pyr_cigna'             => 6.0,
            'pyr_humana'            => 5.5,
            'pyr_medicare'          => 18.5,
            'pyr_medicaid'          => 16.0,
            'pyr_centene'           => 8.0,
            'pyr_molina'            => 2.5,
            'pyr_oscar'             => 0.5,
            'pyr_tricare'           => 2.8,
            'pyr_kaiser'            => 4.0,
            'pyr_anthem'            => 6.5,
            'pyr_hcsc'              => 5.0,
            'pyr_bcbs_il'           => 2.0,
            'pyr_bcbs_tx'           => 2.5,
            'pyr_highmark'          => 2.0,
            'pyr_premera'           => 1.5,
            'pyr_regence'           => 1.5,
            'pyr_florida_blue'      => 3.5,
            'pyr_bcbs_ga'           => 1.8,
            'pyr_carefirst'         => 2.0,
            'pyr_bcbs_ma'           => 2.5,
            'pyr_bcbs_az'           => 1.5,
            'pyr_horizon'           => 2.0,
            'pyr_bcbs_nc'           => 2.5,
            'pyr_bcbs_sc'           => 1.5,
            'pyr_bcbs_tn'           => 2.0,
            'pyr_bcbs_al'           => 1.5,
            'pyr_bcbs_mi'           => 2.0,
            'pyr_bcbs_mn'           => 1.5,
            'pyr_bcbs_la'           => 1.5,
            'pyr_bcbs_ks'           => 1.0,
            'pyr_wellmark'          => 1.0,
            'pyr_independence'      => 1.5,
            'pyr_emblem'            => 1.2,
            'pyr_fidelis'           => 1.0,
            'pyr_healthfirst'       => 1.0,
            'pyr_connecticare'      => 0.8,
            'pyr_harvard_pilgrim'   => 1.0,
            'pyr_tufts'             => 0.8,
            'pyr_mvp'               => 0.6,
            'pyr_amerihealth'       => 1.0,
            'pyr_upmc'              => 1.2,
            'pyr_avmed'             => 0.8,
            'pyr_simply'            => 0.6,
            'pyr_sunshine'          => 1.0,
            'pyr_optima'            => 0.8,
            'pyr_virginia_premier'  => 0.5,
            'pyr_priority_partners' => 0.5,
            'pyr_wellcare'          => 2.5,
            'pyr_caresource'        => 1.2,
            'pyr_medical_mutual'    => 0.8,
            'pyr_priority_health'   => 0.8,
            'pyr_healthpartners'    => 0.8,
            'pyr_hpn'              => 0.5,
            'pyr_mercy_care'        => 0.8,
            'pyr_banner_aetna'      => 0.5,
            'pyr_coordinated_care'  => 0.5,
            'pyr_community_health_wa' => 0.4,
            'pyr_providence'        => 0.6,
            'pyr_moda'              => 0.4,
            'pyr_superior'          => 1.0,
            'pyr_healthy_blue'      => 0.8,
        ];

        $now = now();

        foreach ($payers as $payer) {
            $payer['market_share'] = $marketShares[$payer['slug']] ?? null;
            DB::table('payers')->updateOrInsert(
                ['slug' => $payer['slug']],
                array_merge($payer, [
                    'created_at' => $now,
                ])
            );
        }
    }
}
