<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PayerSeeder extends Seeder
{
    /**
     * Seed the payers table with the full Providus payer catalog.
     */
    public function run(): void
    {
        $payers = [
            // ── NATIONAL — BIG 5 ──
            [
                'slug'              => 'pyr_uhc',
                'name'              => 'UnitedHealthcare',
                'category'          => 'national',
                'region'            => 'national',
                'parent_org'        => 'UnitedHealth Group',
                'stedi_id'          => '87726',
                'states'            => json_encode(['ALL']),
                'avg_cred_days'     => 90,
                'credentialing_url' => 'https://www.uhcprovider.com',
            ],
            [
                'slug'              => 'pyr_aetna',
                'name'              => 'Aetna',
                'category'          => 'national',
                'region'            => 'national',
                'parent_org'        => 'CVS Health',
                'stedi_id'          => '60054',
                'states'            => json_encode(['ALL']),
                'avg_cred_days'     => 75,
                'credentialing_url' => 'https://www.availity.com',
            ],
            [
                'slug'              => 'pyr_cigna',
                'name'              => 'Cigna',
                'category'          => 'national',
                'region'            => 'national',
                'parent_org'        => 'The Cigna Group / Evernorth',
                'stedi_id'          => '62308',
                'states'            => json_encode(['ALL']),
                'avg_cred_days'     => 60,
                'credentialing_url' => 'https://cignaforhcp.cigna.com',
            ],
            [
                'slug'              => 'pyr_humana',
                'name'              => 'Humana',
                'category'          => 'national',
                'region'            => 'national',
                'parent_org'        => 'Humana',
                'stedi_id'          => '61101',
                'states'            => json_encode(['ALL']),
                'avg_cred_days'     => 60,
                'credentialing_url' => 'https://provider.humana.com',
            ],
            [
                'slug'              => 'pyr_medicare',
                'name'              => 'Medicare',
                'category'          => 'national',
                'region'            => 'national',
                'parent_org'        => 'CMS',
                'stedi_id'          => 'CMS',
                'states'            => json_encode(['ALL']),
                'avg_cred_days'     => 120,
                'credentialing_url' => 'https://pecos.cms.hhs.gov',
            ],

            // ── NATIONAL — MANAGED CARE / ACA ──
            [
                'slug'              => 'pyr_centene',
                'name'              => 'Centene/Ambetter',
                'category'          => 'national',
                'region'            => 'national',
                'parent_org'        => 'Centene Corporation',
                'stedi_id'          => 'AMB01',
                'states'            => json_encode(['ALL']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_molina',
                'name'              => 'Molina Healthcare',
                'category'          => 'national',
                'region'            => 'national',
                'parent_org'        => 'Molina Healthcare',
                'stedi_id'          => 'MOLIN',
                'states'            => json_encode(['ALL']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_oscar',
                'name'              => 'Oscar Health',
                'category'          => 'national',
                'region'            => 'national',
                'parent_org'        => 'Oscar Health',
                'stedi_id'          => 'OSCAR',
                'states'            => json_encode(['ALL']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_tricare',
                'name'              => 'Tricare',
                'category'          => 'national',
                'region'            => 'national',
                'parent_org'        => 'DoD / DHA',
                'stedi_id'          => 'TRIC',
                'states'            => json_encode(['ALL']),
                'avg_cred_days'     => 90,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_kaiser',
                'name'              => 'Kaiser Permanente',
                'category'          => 'national',
                'region'            => 'west',
                'parent_org'        => 'Kaiser Foundation',
                'stedi_id'          => null,
                'states'            => json_encode(['CA', 'CO', 'GA', 'HI', 'MD', 'OR', 'VA', 'WA', 'DC']),
                'avg_cred_days'     => 90,
                'credentialing_url' => null,
            ],

            // ── BCBS — ANTHEM/ELEVANCE ──
            [
                'slug'              => 'pyr_anthem',
                'name'              => 'Anthem/Elevance',
                'category'          => 'bcbs_anthem',
                'region'            => 'national',
                'parent_org'        => 'Elevance Health',
                'stedi_id'          => null,
                'states'            => json_encode(['CA', 'CO', 'CT', 'GA', 'IN', 'KY', 'ME', 'MO', 'NV', 'NH', 'NY', 'OH', 'VA', 'WI']),
                'avg_cred_days'     => 90,
                'credentialing_url' => 'https://www.availity.com',
            ],

            // ── BCBS — HCSC ──
            [
                'slug'              => 'pyr_hcsc',
                'name'              => 'HCSC',
                'category'          => 'bcbs_hcsc',
                'region'            => 'midwest',
                'parent_org'        => 'Health Care Service Corporation',
                'stedi_id'          => null,
                'states'            => json_encode(['TX', 'IL', 'OK', 'NM', 'MT']),
                'avg_cred_days'     => 90,
                'credentialing_url' => 'https://www.bcbsil.com/provider',
            ],

            // ── BCBS — HIGHMARK ──
            [
                'slug'              => 'pyr_highmark',
                'name'              => 'Highmark BCBS',
                'category'          => 'bcbs_highmark',
                'region'            => 'northeast',
                'parent_org'        => 'Highmark Health',
                'stedi_id'          => null,
                'states'            => json_encode(['PA', 'DE', 'WV', 'NY']),
                'avg_cred_days'     => 75,
                'credentialing_url' => 'https://www.availity.com',
            ],

            // ── BCBS — PREMERA / REGENCE ──
            [
                'slug'              => 'pyr_premera',
                'name'              => 'Premera Blue Cross',
                'category'          => 'bcbs_independent',
                'region'            => 'pacific_nw',
                'parent_org'        => 'Premera',
                'stedi_id'          => null,
                'states'            => json_encode(['WA', 'AK']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_regence',
                'name'              => 'Regence BlueShield',
                'category'          => 'bcbs_independent',
                'region'            => 'pacific_nw',
                'parent_org'        => 'Cambia Health Solutions',
                'stedi_id'          => null,
                'states'            => json_encode(['WA', 'OR', 'UT', 'ID']),
                'avg_cred_days'     => 60,
                'credentialing_url' => 'https://www.availity.com',
            ],

            // ── BCBS — INDEPENDENT STATE PLANS ──
            [
                'slug'              => 'pyr_florida_blue',
                'name'              => 'Florida Blue',
                'category'          => 'bcbs_independent',
                'region'            => 'southeast',
                'parent_org'        => 'GuideWell',
                'stedi_id'          => null,
                'states'            => json_encode(['FL']),
                'avg_cred_days'     => 60,
                'credentialing_url' => 'https://www.availity.com',
            ],
            [
                'slug'              => 'pyr_carefirst',
                'name'              => 'CareFirst BCBS',
                'category'          => 'bcbs_independent',
                'region'            => 'northeast',
                'parent_org'        => 'CareFirst',
                'stedi_id'          => null,
                'states'            => json_encode(['MD', 'DC', 'VA']),
                'avg_cred_days'     => 60,
                'credentialing_url' => 'https://provider.carefirst.com',
            ],
            [
                'slug'              => 'pyr_bcbs_ma',
                'name'              => 'BCBS of Massachusetts',
                'category'          => 'bcbs_independent',
                'region'            => 'northeast',
                'parent_org'        => 'BCBS MA',
                'stedi_id'          => null,
                'states'            => json_encode(['MA']),
                'avg_cred_days'     => 60,
                'credentialing_url' => 'https://provider.bluecrossma.com',
            ],
            [
                'slug'              => 'pyr_bcbs_az',
                'name'              => 'BCBS of Arizona',
                'category'          => 'bcbs_independent',
                'region'            => 'west',
                'parent_org'        => 'BCBS AZ',
                'stedi_id'          => null,
                'states'            => json_encode(['AZ']),
                'avg_cred_days'     => 60,
                'credentialing_url' => 'https://credentialing.azblue.com',
            ],
            [
                'slug'              => 'pyr_horizon',
                'name'              => 'Horizon BCBS',
                'category'          => 'bcbs_independent',
                'region'            => 'northeast',
                'parent_org'        => 'Horizon',
                'stedi_id'          => null,
                'states'            => json_encode(['NJ']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_bcbs_nc',
                'name'              => 'BCBS of North Carolina',
                'category'          => 'bcbs_independent',
                'region'            => 'southeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['NC']),
                'avg_cred_days'     => 75,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_bcbs_sc',
                'name'              => 'BCBS of South Carolina',
                'category'          => 'bcbs_independent',
                'region'            => 'southeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['SC']),
                'avg_cred_days'     => 75,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_bcbs_tn',
                'name'              => 'BCBS of Tennessee',
                'category'          => 'bcbs_independent',
                'region'            => 'southeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['TN']),
                'avg_cred_days'     => 75,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_bcbs_al',
                'name'              => 'BCBS of Alabama',
                'category'          => 'bcbs_independent',
                'region'            => 'southeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['AL']),
                'avg_cred_days'     => 75,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_bcbs_mi',
                'name'              => 'BCBS of Michigan',
                'category'          => 'bcbs_independent',
                'region'            => 'midwest',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['MI']),
                'avg_cred_days'     => 75,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_bcbs_mn',
                'name'              => 'BCBS of Minnesota',
                'category'          => 'bcbs_independent',
                'region'            => 'midwest',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['MN']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_bcbs_la',
                'name'              => 'BCBS of Louisiana',
                'category'          => 'bcbs_independent',
                'region'            => 'south',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['LA']),
                'avg_cred_days'     => 75,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_bcbs_ks',
                'name'              => 'BCBS of Kansas',
                'category'          => 'bcbs_independent',
                'region'            => 'midwest',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['KS']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_wellmark',
                'name'              => 'Wellmark BCBS',
                'category'          => 'bcbs_independent',
                'region'            => 'midwest',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['IA', 'SD']),
                'avg_cred_days'     => 60,
                'credentialing_url' => 'https://www.wellmark.com/e-cred/index.aspx',
            ],
            [
                'slug'              => 'pyr_independence',
                'name'              => 'Independence Blue Cross',
                'category'          => 'bcbs_independent',
                'region'            => 'northeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['PA']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
            ],

            // ── REGIONAL — NORTHEAST ──
            [
                'slug'              => 'pyr_emblem',
                'name'              => 'EmblemHealth',
                'category'          => 'regional',
                'region'            => 'northeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['NY']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_fidelis',
                'name'              => 'Fidelis Care',
                'category'          => 'regional',
                'region'            => 'northeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['NY']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_healthfirst',
                'name'              => 'Healthfirst',
                'category'          => 'regional',
                'region'            => 'northeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['NY']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_connecticare',
                'name'              => 'ConnectiCare',
                'category'          => 'regional',
                'region'            => 'northeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['CT']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_harvard_pilgrim',
                'name'              => 'Harvard Pilgrim',
                'category'          => 'regional',
                'region'            => 'northeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['MA', 'NH', 'ME', 'CT']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_tufts',
                'name'              => 'Tufts Health Plan',
                'category'          => 'regional',
                'region'            => 'northeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['MA']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_mvp',
                'name'              => 'MVP Health Care',
                'category'          => 'regional',
                'region'            => 'northeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['NY', 'VT']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_amerihealth',
                'name'              => 'AmeriHealth',
                'category'          => 'regional',
                'region'            => 'northeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['PA', 'NJ', 'DE']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_upmc',
                'name'              => 'UPMC Health Plan',
                'category'          => 'regional',
                'region'            => 'northeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['PA']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
            ],

            // ── REGIONAL — SOUTHEAST ──
            [
                'slug'              => 'pyr_avmed',
                'name'              => 'AvMed',
                'category'          => 'regional',
                'region'            => 'southeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['FL']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_simply',
                'name'              => 'Simply Healthcare',
                'category'          => 'regional',
                'region'            => 'southeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['FL']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_sunshine',
                'name'              => 'Sunshine Health',
                'category'          => 'regional',
                'region'            => 'southeast',
                'parent_org'        => 'Centene',
                'stedi_id'          => null,
                'states'            => json_encode(['FL']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_optima',
                'name'              => 'Optima Health',
                'category'          => 'regional',
                'region'            => 'southeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['VA']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_virginia_premier',
                'name'              => 'Virginia Premier',
                'category'          => 'regional',
                'region'            => 'southeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['VA']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_priority_partners',
                'name'              => 'Priority Partners',
                'category'          => 'regional',
                'region'            => 'northeast',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['MD']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_wellcare',
                'name'              => 'WellCare',
                'category'          => 'regional',
                'region'            => 'southeast',
                'parent_org'        => 'Centene',
                'stedi_id'          => null,
                'states'            => json_encode(['FL', 'GA', 'KY', 'NY', 'TX']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
            ],

            // ── REGIONAL — MIDWEST ──
            [
                'slug'              => 'pyr_caresource',
                'name'              => 'CareSource',
                'category'          => 'regional',
                'region'            => 'midwest',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['OH', 'IN', 'GA', 'KY', 'WV']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_medical_mutual',
                'name'              => 'Medical Mutual',
                'category'          => 'regional',
                'region'            => 'midwest',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['OH']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_priority_health',
                'name'              => 'Priority Health',
                'category'          => 'regional',
                'region'            => 'midwest',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['MI']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_healthpartners',
                'name'              => 'HealthPartners',
                'category'          => 'regional',
                'region'            => 'midwest',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['MN', 'WI']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
            ],

            // ── REGIONAL — WEST / MOUNTAIN ──
            [
                'slug'              => 'pyr_hpn',
                'name'              => 'Health Plan of Nevada',
                'category'          => 'regional',
                'region'            => 'west',
                'parent_org'        => 'UnitedHealth Group',
                'stedi_id'          => null,
                'states'            => json_encode(['NV']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_mercy_care',
                'name'              => 'Mercy Care',
                'category'          => 'regional',
                'region'            => 'west',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['AZ']),
                'avg_cred_days'     => 45,
                'credentialing_url' => 'https://www.availity.com',
            ],
            [
                'slug'              => 'pyr_banner_aetna',
                'name'              => 'Banner | Aetna',
                'category'          => 'regional',
                'region'            => 'west',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['AZ']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
            ],

            // ── REGIONAL — PACIFIC NW ──
            [
                'slug'              => 'pyr_coordinated_care',
                'name'              => 'Coordinated Care',
                'category'          => 'regional',
                'region'            => 'pacific_nw',
                'parent_org'        => 'Centene',
                'stedi_id'          => null,
                'states'            => json_encode(['WA']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_community_health_wa',
                'name'              => 'Community Health Plan of WA',
                'category'          => 'regional',
                'region'            => 'pacific_nw',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['WA']),
                'avg_cred_days'     => 45,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_providence',
                'name'              => 'Providence Health Plan',
                'category'          => 'regional',
                'region'            => 'pacific_nw',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['OR', 'WA']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_moda',
                'name'              => 'Moda Health',
                'category'          => 'regional',
                'region'            => 'pacific_nw',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['OR', 'AK']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
            ],

            // ── REGIONAL — SOUTH / TX ──
            [
                'slug'              => 'pyr_superior',
                'name'              => 'Superior HealthPlan',
                'category'          => 'regional',
                'region'            => 'south',
                'parent_org'        => 'Centene',
                'stedi_id'          => null,
                'states'            => json_encode(['TX']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
            ],
            [
                'slug'              => 'pyr_healthy_blue',
                'name'              => 'Healthy Blue',
                'category'          => 'regional',
                'region'            => 'south',
                'parent_org'        => null,
                'stedi_id'          => null,
                'states'            => json_encode(['LA', 'NC', 'SC']),
                'avg_cred_days'     => 60,
                'credentialing_url' => null,
            ],
        ];

        $now = now();

        foreach ($payers as $payer) {
            DB::table('payers')->updateOrInsert(
                ['slug' => $payer['slug']],
                array_merge($payer, [
                    'created_at' => $now,
                    'updated_at' => $now,
                ])
            );
        }
    }
}
